### ISSUE TITLE
Pulling recipes and display

### ISSUE THREAD

**Issue by azuryte5** [azuryte5/Nutrition-Sustenance-Value#14]
Links get shown 
Once you pick one a page gets shown to show nutritional facts

**Comment by azuryte5** [comment]
recipe being pulled from api fetch (servings, image, ingredients, link to site (not working yet))

**Comment by jhugray** [comment]
Recipe cards are now generated and fully operational (nutrition info to be added), link to recipe working. I'd suggest we just add the nutritional info to each of the 3 recipe cards, so that when comparing the recipes, they can utilize the nutritional info to make an informed decision about which meal they wish to make.
